import type { Song } from './types';
import { InstrumentType } from './types';

// ====================================================================================
// ESTRATÉGIA DE ÁUDIO ATUALIZADA:
// Conforme solicitado, todos os links de demonstração foram removidos.
// O aplicativo agora só tentará carregar áudios com links diretos fornecidos pelo usuário.
// Instrumentos sem um 'path' serão silenciosos e não causarão erros.
// ====================================================================================

export const SONGS: Song[] = [
  {
    id: 2,
    name: "Baobá Ancestral",
    artist: "Malungos do Interior",
    bpm: 120,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-backing-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-baixo.mp3' },
        { id: 4, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-berimbau.mp3' },
        { id: 5, instrument: "Caixas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-caixas.mp3' },
        { id: 6, instrument: "Caxixi", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-caxixi.mp3' },
        { id: 7, instrument: "Conga", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-conga.mp3' },
        { id: 8, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-cowbell.mp3' },
        { id: 9, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-clean.mp3' },
        { id: 10, instrument: "Guitarra Distorcida", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-dist.mp3' },
        { id: 11, instrument: "Participação", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-participacao.mp3' },
        { id: 12, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-pratos.mp3' },
        { id: 13, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-tri%C3%A2ngulo.mp3' },
        { id: 14, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-violoes.mp3' },
        { id: 15, instrument: "Xequerê 1", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-xequere-1.mp3' },
        { id: 16, instrument: "Xequerê 2", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/baoba-ancestral/%5Bbaoba-ancestral%5D-xequere-2.mp3' },
    ],
  },
  {
    id: 3,
    name: "Batuque de Malungo",
    artist: "Malungos do Interior",
    bpm: 135,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Agogô", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-agogo.mp3' },
        { id: 2, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-alfaia.mp3' },
        { id: 3, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-backing-vocals.mp3' },
        { id: 4, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-baixo.mp3' },
        { id: 5, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-berimbau.mp3' },
        { id: 6, instrument: "Bomb", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-bomb.mp3' },
        { id: 7, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-caixa.mp3' },
        { id: 8, instrument: "Conga", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-conga.mp3' },
        { id: 9, instrument: "Guitarra Distorcida", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-dist.mp3' },
        { id: 10, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-clean.mp3' },
        { id: 11, instrument: "Nzila", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-nzila.mp3' },
        { id: 12, instrument: "Palmas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-palmas.mp3' },
        { id: 13, instrument: "Pandeiro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-pandeiro.mp3' },
        { id: 14, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-violoes.mp3' },
        { id: 15, instrument: "Woosh", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-woosh.mp3' },
        { id: 16, instrument: "Xequerê 1", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-xequere-1.mp3' },
        { id: 17, instrument: "Xequerê 2", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/batuque-de-malungo/%5Bbatuque-de-malungo%5D-xequere-2.mp3' },
    ],
  },
  {
    id: 5,
    name: "Pé de Coco",
    artist: "Malungos do Interior",
    bpm: 110,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dbacking_vocals.mp3' },
      { id: 2, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dbass.mp3' },
      { id: 3, instrument: "Bateria", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Ddrums.mp3' },
      { id: 4, instrument: "Guitarras", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dguitars.mp3' },
      { id: 5, instrument: "Metrônomo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dmetronome.mp3' },
      { id: 6, instrument: "Outros", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dother.mp3' },
      { id: 7, instrument: "Vocal", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dvocals.mp3' },
    ],
  },
  {
    id: 4,
    name: "Boia Fria",
    artist: "Malungos do Interior",
    bpm: 95,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-cowbell.mp3' },
      { id: 8, instrument: "Efeitos e Intro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-efeitos-e-intro.mp3' },
      { id: 9, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-guitas-clean.mp3' },
      { id: 10, instrument: "Guitarra Distorcida", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-guitas-dist.mp3' },
      { id: 11, instrument: "Pandeiro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-pandeiro.mp3' },
      { id: 12, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-triangulo.mp3' },
      { id: 13, instrument: "Violões Aço", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-violoes-aco.mp3' },
      { id: 14, instrument: "Xequerê 1", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-xequere-1.mp3' },
      { id: 15, instrument: "Xequerê 2", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/boia-fria/%5Bboia-fria%5D-xequere-2.mp3' },
    ],
  },
  {
    id: 1,
    name: "A Escolha é Nossa",
    artist: "Malungos do Interior",
    bpm: 80,
    timeSignature: [3, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-backings-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-baixo.mp3' },
        { id: 4, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-caixa.mp3' },
        { id: 5, instrument: "Conga", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-conga.mp3' },
        { id: 6, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-cowbell.mp3' },
        { id: 7, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-clean.mp3' },
        { id: 8, instrument: "Guitarra Distorcida", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-dist.mp3' },
        { id: 9, instrument: "Sintetizador", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-sinth.mp3' },
        { id: 10, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-triangulo.mp3' },
        { id: 11, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-violoes.mp3' },
        { id: 12, instrument: "Xequerê 1", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-xequere-1.mp3' },
        { id: 13, instrument: "Xequerê 2", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/master/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-xequere-2.mp3' },
    ],
  },
];
