
import type { Song } from './types';

// ====================================================================================
// ESTRATÉGIA DE ÁUDIO:
// Links atualizados conforme solicitação do usuário.
// As músicas agora contém todas as faixas separadas (multitracks) para mixagem.
// ====================================================================================

export const SONGS: Song[] = [
  {
    id: 1,
    name: "A Escolha é Nossa",
    artist: "Malungos do Interior",
    bpm: 80,
    timeSignature: [3, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-backing-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-baixo.mp3' },
        { id: 4, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-caixa.mp3' },
        { id: 5, instrument: "Congas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-congas.mp3' },
        { id: 6, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-cowbell.mp3' },
        { id: 7, instrument: "Guitarra Base", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-base.mp3' },
        { id: 8, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-clean.mp3' },
        { id: 9, instrument: "Guitarra Solo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-solo-final.mp3' },
        { id: 10, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-pratos.mp3' },
        { id: 11, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-triangulo.mp3' },
        { id: 12, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-violoes.mp3' },
        { id: 13, instrument: "Voz", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-vocal.mp3' },
        { id: 14, instrument: "Xequerê", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-xequeres.mp3' },
    ],
  },
  {
    id: 2,
    name: "Baobá Ancestral",
    artist: "Malungos do Interior",
    bpm: 120,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-backing-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-baixo.mp3' },
        { id: 4, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-berimbau.mp3' },
        { id: 5, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-caixas.mp3' },
        { id: 6, instrument: "Caxixi", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-caxixi.mp3' },
        { id: 7, instrument: "Congas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-congas.mp3' },
        { id: 8, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-cowbell.mp3' },
        { id: 9, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-clean.mp3' },
        { id: 10, instrument: "Guitarra Dist.", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-distorcao.mp3' },
        { id: 11, instrument: "Guitarra Solo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-solo.mp3' },
        { id: 12, instrument: "Participação", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-participacao.mp3' },
        { id: 13, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-pratos.mp3' },
        { id: 14, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-triangulo.mp3' },
        { id: 15, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-violoes.mp3' },
        { id: 16, instrument: "Voz", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-vocal.mp3' },
        { id: 17, instrument: "Voz Texto", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-vocal-texto.mp3' },
        { id: 18, instrument: "Xequerê", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-xequeres.mp3' },
    ],
  },
  {
    id: 3,
    name: "Batuque de Malungo",
    artist: "Malungos do Interior",
    bpm: 135,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Agogô", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-agogo.mp3' },
        { id: 2, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-alfaia.mp3' },
        { id: 3, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-backing-vocals.mp3' },
        { id: 4, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-baixo.mp3' },
        { id: 5, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-berimbau.mp3' },
        { id: 6, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-caixa.mp3' },
        { id: 7, instrument: "Conga", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-conga.mp3' },
        { id: 8, instrument: "Efeitos Sonoros", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-efeitos-sonoros.mp3' },
        { id: 9, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-clean.mp3' },
        { id: 10, instrument: "Guitarra Dist.", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-distorcao.mp3' },
        { id: 11, instrument: "Nzila", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-nzila.mp3' },
        { id: 12, instrument: "Palmas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-palmas.mp3' },
        { id: 13, instrument: "Pandeiro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-pandeiro.mp3' },
        { id: 14, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-pratos.mp3' },
        { id: 15, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-violoes.mp3' },
        { id: 16, instrument: "Voz", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-vocal.mp3' },
        { id: 17, instrument: "Voz Texto", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-vocal-texto.mp3' },
        { id: 18, instrument: "Xequerê", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-xequeres.mp3' },
    ],
  },
  {
    id: 4,
    name: "Boia Fria",
    artist: "Malungos do Interior",
    bpm: 95,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-caixa.mp3' },
      { id: 6, instrument: "Congas", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-congas.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-cowbell.mp3' },
      { id: 8, instrument: "Guit. Clean 1", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-clean-1.mp3' },
      { id: 9, instrument: "Guit. Clean 2", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-clean-2.mp3' },
      { id: 10, instrument: "Gt Delay/Ponte", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-delay-efeito-ponte.mp3' },
      { id: 11, instrument: "Gt Dist/Base", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-distorcao-base-final.mp3' },
      { id: 12, instrument: "Gt Psicodel", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-psicodel-ponte.mp3' },
      { id: 13, instrument: "Gt Tema", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-tema-principal.mp3' },
      { id: 14, instrument: "Gt Tema Final", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-tema-verso-final.mp3' },
      { id: 15, instrument: "Intro/Efeitos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-intro-e-efeitos-sonoros.mp3' },
      { id: 16, instrument: "Pandeiro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-pandeiro.mp3' },
      { id: 17, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-pratos.mp3' },
      { id: 18, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-triangulo.mp3' },
      { id: 19, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-violoes.mp3' },
      { id: 20, instrument: "Voz", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-vocal.mp3' },
      { id: 21, instrument: "Voz Final", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-vocal-parte-final.mp3' },
      { id: 22, instrument: "Xequerê", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-xequeres.mp3' },
    ],
  },
  {
    id: 5,
    name: "Pé de Coco",
    artist: "Malungos do Interior",
    bpm: 110,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Agogô", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dagogo.mp3' },
      { id: 2, instrument: "Alfaia", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dalfaia.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dbacking-vocals.mp3' },
      { id: 4, instrument: "Baixo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dbaixo.mp3' },
      { id: 5, instrument: "Berimbau", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dberimbau.mp3' },
      { id: 6, instrument: "Caixa", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dcaixa.mp3' },
      { id: 7, instrument: "Guitarra Clean", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dguitas-clean.mp3' },
      { id: 8, instrument: "Guitarra Dist.", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dguitas-distorcao.mp3' },
      { id: 9, instrument: "Guitarra Tema", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dguitas-tema.mp3' },
      { id: 10, instrument: "Guitarra Wah", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dguitas-wah.mp3' },
      { id: 11, instrument: "Pandeiro", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dpandeiro.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dpratos.mp3' },
      { id: 13, instrument: "Queixada", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dqueixada.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dtriangulo.mp3' },
      { id: 15, instrument: "Violões", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dvioloes.mp3' },
      { id: 16, instrument: "Voz", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dvocal.mp3' },
      { id: 17, instrument: "Xequerê", path: 'https://raw.githubusercontent.com/BesouroLAB/albumsankofa/main/pe-de%20coco/%5Bp%C3%A9%20de%20coco%5Dxequeres.mp3' },
    ],
  },
];
