
import type { Song } from './types';

// ====================================================================================
// ESTRATÉGIA DE ÁUDIO:
// Links atualizados conforme solicitação do usuário.
// As músicas agora contém todas as faixas separadas (multitracks) para mixagem.
// ====================================================================================

export const SONGS: Song[] = [
  {
    id: 1,
    name: "A Escolha é Nossa",
    artist: "Malungos do Interior",
    bpm: 80,
    timeSignature: [3, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-backing-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-baixo.mp3' },
        { id: 4, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-caixa.mp3' },
        { id: 5, instrument: "Congas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-congas.mp3' },
        { id: 6, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-cowbell.mp3' },
        { id: 7, instrument: "Guitarra Base", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-base.mp3' },
        { id: 8, instrument: "Guitarra Clean", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-clean.mp3' },
        { id: 9, instrument: "Guitarra Solo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-guitas-solo-final.mp3' },
        { id: 10, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-pratos.mp3' },
        { id: 11, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-triangulo.mp3' },
        { id: 12, instrument: "Violões", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-violoes.mp3' },
        { id: 13, instrument: "Voz", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-vocal.mp3' },
        { id: 14, instrument: "Xequerê", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/a-escolha-e-nossa/%5Ba-escolha-e-nossa%5D-xequeres.mp3' },
    ],
  },
  {
    id: 2,
    name: "Baobá Ancestral",
    artist: "Malungos do Interior",
    bpm: 120,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-alfaia.mp3' },
        { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-backing-vocals.mp3' },
        { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-baixo.mp3' },
        { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-berimbau.mp3' },
        { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-caixas.mp3' },
        { id: 6, instrument: "Caxixi", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-caxixi.mp3' },
        { id: 7, instrument: "Congas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-congas.mp3' },
        { id: 8, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-cowbell.mp3' },
        { id: 9, instrument: "Guitarra Clean", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-clean.mp3' },
        { id: 10, instrument: "Guitarra Dist.", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-distorcao.mp3' },
        { id: 11, instrument: "Guitarra Solo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-guitas-solo.mp3' },
        { id: 12, instrument: "Participação", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-participacao.mp3' },
        { id: 13, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-pratos.mp3' },
        { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-triangulo.mp3' },
        { id: 15, instrument: "Violões", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-violoes.mp3' },
        { id: 16, instrument: "Voz", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-vocal.mp3' },
        { id: 17, instrument: "Voz Texto", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-vocal-texto.mp3' },
        { id: 18, instrument: "Xequerê", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/baoba-ancestral/%5Bbaoba-ancestral%5D-xequeres.mp3' },
    ],
  },
  {
    id: 3,
    name: "Batuque de Malungo",
    artist: "Malungos do Interior",
    bpm: 135,
    timeSignature: [4, 4],
    tracks: [
        { id: 1, instrument: "Agogô", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-agogo.mp3' },
        { id: 2, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-alfaia.mp3' },
        { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-backing-vocals.mp3' },
        { id: 4, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-baixo.mp3' },
        { id: 5, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-berimbau.mp3' },
        { id: 6, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-caixa.mp3' },
        { id: 7, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-conga.mp3' },
        { id: 8, instrument: "Efeitos Sonoros", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-efeitos-sonoros.mp3' },
        { id: 9, instrument: "Guitarra Clean", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-clean.mp3' },
        { id: 10, instrument: "Guitarra Dist.", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-guitas-distorcao.mp3' },
        { id: 11, instrument: "Nzila", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-nzila.mp3' },
        { id: 12, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-palmas.mp3' },
        { id: 13, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-pandeiro.mp3' },
        { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-pratos.mp3' },
        { id: 15, instrument: "Violões", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-violoes.mp3' },
        { id: 16, instrument: "Voz", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-vocal.mp3' },
        { id: 17, instrument: "Voz Texto", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-vocal-texto.mp3' },
        { id: 18, instrument: "Xequerê", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/batuque-de-malungo/%5Bbatuque-de-malungo%5D-xequeres.mp3' },
    ],
  },
  {
    id: 4,
    name: "Boia Fria",
    artist: "Malungos do Interior",
    bpm: 95,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-caixa.mp3' },
      { id: 6, instrument: "Congas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-congas.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-cowbell.mp3' },
      { id: 8, instrument: "Guit. Clean 1", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-clean-1.mp3' },
      { id: 9, instrument: "Guit. Clean 2", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-clean-2.mp3' },
      { id: 10, instrument: "Gt Delay/Ponte", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-delay-efeito-ponte.mp3' },
      { id: 11, instrument: "Gt Dist/Base", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-distorcao-base-final.mp3' },
      { id: 12, instrument: "Gt Psicodel", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-psicodel-ponte.mp3' },
      { id: 13, instrument: "Gt Tema", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-tema-principal.mp3' },
      { id: 14, instrument: "Gt Tema Final", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-guitas-tema-verso-final.mp3' },
      { id: 15, instrument: "Intro/Efeitos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-intro-e-efeitos-sonoros.mp3' },
      { id: 16, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-pandeiro.mp3' },
      { id: 17, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-pratos.mp3' },
      { id: 18, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-triangulo.mp3' },
      { id: 19, instrument: "Violões", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-violoes.mp3' },
      { id: 20, instrument: "Voz", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-vocal.mp3' },
      { id: 21, instrument: "Voz Final", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-vocal-parte-final.mp3' },
      { id: 22, instrument: "Xequerê", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/boia-fria/%5Bboia-fria%5D-xequeres.mp3' },
    ],
  },
  {
    id: 5,
    name: "Pé de Coco",
    artist: "Malungos do Interior",
    bpm: 110,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Agogô", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-agogo.mp3' },
      { id: 2, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-alfaia.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-baixo.mp3' },
      { id: 5, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-berimbau.mp3' },
      { id: 6, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-caixa.mp3' },
      { id: 7, instrument: "Guitarra Clean", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-guitas-clean.mp3' },
      { id: 8, instrument: "Guitarra Dist.", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-guitas-distorcao.mp3' },
      { id: 9, instrument: "Guitarra Tema", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-guitas-tema.mp3' },
      { id: 10, instrument: "Guitarra Wah", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-guitas-wah.mp3' },
      { id: 11, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-pandeiro.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-pratos.mp3' },
      { id: 13, instrument: "Queixada", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-queixada.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-triangulo.mp3' },
      { id: 15, instrument: "Violões", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-violoes.mp3' },
      { id: 16, instrument: "Voz", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-vocal.mp3' },
      { id: 17, instrument: "Xequerê", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/pe-de-coco/%5Bpe-de-coco%5D-xequeres.mp3' },
    ],
  },
];

export const SHOW_SONGS: Song[] = [
  {
    id: 101,
    name: "01. Rei Precioso / Batuque de Malungo",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-cowbell.mp3' },
      { id: 8, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-guitarra.mp3' },
      { id: 9, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-palmas.mp3' },
      { id: 10, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-pandeiro.mp3' },
      { id: 11, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-percussoes-originais.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-pratos.mp3' },
      { id: 13, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-regencia.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-triangulo.mp3' },
      { id: 15, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-violao.mp3' },
      { id: 16, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-vocal.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/01-rei-precioso-batuque-de-malungo/%5B01-rei-precioso-batuque-de-malungo%5D-xequeres.mp3' },
    ],
  },
  {
    id: 102,
    name: "02. Baobá Ancestral",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/02-baoba-ancestral/%5B02-baoba-ancestral%5D-xequeres.mp3' },
    ],
  },
  {
    id: 103,
    name: "03. Pé de Coco / Baião Ambiental",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-cowbell.mp3' },
      { id: 8, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-guitarra.mp3' },
      { id: 9, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-palmas.mp3' },
      { id: 10, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-pandeiro.mp3' },
      { id: 11, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-percussoes-originais.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-pratos.mp3' },
      { id: 13, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-regencia.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-triangulo.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/03-pe-de-coco-baiao-ambiental/%5B03-pe-de-coco-baiao-ambiental%5D-xequeres.mp3' },
    ],
  },
  {
    id: 104,
    name: "04. Nove Cirandas / Caio no Swing",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-cowbell.mp3' },
      { id: 8, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-guitarra.mp3' },
      { id: 9, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-palmas.mp3' },
      { id: 10, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-pandeiro.mp3' },
      { id: 11, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-percussoes-originais.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-pratos.mp3' },
      { id: 13, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-regencia.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-triangulo.mp3' },
      { id: 15, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-violao.mp3' },
      { id: 16, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-vocal.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/04-nove-cirandas-caio-no-swing/%5B04-nove-cirandas-caio-no-swing%5D-xequeres.mp3' },
    ],
  },
  {
    id: 105,
    name: "05. Homem Amarelo",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-cowbell.mp3' },
      { id: 8, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-guitarra.mp3' },
      { id: 9, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-palmas.mp3' },
      { id: 10, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-pandeiro.mp3' },
      { id: 11, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-percussoes-originais.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-pratos.mp3' },
      { id: 13, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-regencia.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-triangulo.mp3' },
      { id: 15, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-violao.mp3' },
      { id: 16, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-vocal.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/05-homem-amarelo/%5B05-homem-amarelo%5D-xequeres.mp3' },
    ],
  },
  {
    id: 106,
    name: "06. O Boia Fria",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-alfaia.mp3' },
      { id: 2, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-backing-vocals.mp3' },
      { id: 3, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-baixo.mp3' },
      { id: 4, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-berimbau.mp3' },
      { id: 5, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-caixa.mp3' },
      { id: 6, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-conga.mp3' },
      { id: 7, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-cowbell.mp3' },
      { id: 8, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-guitarra.mp3' },
      { id: 9, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-palmas.mp3' },
      { id: 10, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-pandeiro.mp3' },
      { id: 11, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-percussoes-originais.mp3' },
      { id: 12, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-pratos.mp3' },
      { id: 13, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-regencia.mp3' },
      { id: 14, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-triangulo.mp3' },
      { id: 15, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-violao.mp3' },
      { id: 16, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-vocal.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/06-o-boia-fria/%5B06-o-boia-fria%5D-xequeres.mp3' },
    ],
  },
  {
    id: 107,
    name: "07. Manguetown",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/07-manguetown/%5B07-manguetown%5D-xequeres.mp3' },
    ],
  },
  {
    id: 108,
    name: "08. Maracatu Atômico",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/08-maracatu-atomico/%5B08-maracatu-atomico%5D-xequeres.mp3' },
    ],
  },
  {
    id: 109,
    name: "09. Canto das Três Raças / Zumbi",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/09-canto-das-tres-racas-zumbi/%5B09-canto-das-tres-racas-zumbi%5D-xequeres.mp3' },
    ],
  },
  {
    id: 110,
    name: "10. A Escolha é Nossa",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/10-a-escolha-e-nossa/%5B10-a-escolha-e-nossa%5D-xequeres.mp3' },
    ],
  },
  {
    id: 111,
    name: "11. Monólogo Banditismo / Quilombo Groove",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/11-monologo-banditismo-quilombo-groove/%5B11-monologo-banditismo-quilombo-groove%5D-xequeres.mp3' },
    ],
  },
  {
    id: 112,
    name: "12. Praieira",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/12-praieira/%5B12-praieira%5D-xequeres.mp3' },
    ],
  },
  {
    id: 113,
    name: "13. Pra Cordel e Naná / Poeira",
    artist: "Nação Sankofa Baobá",
    bpm: 0,
    timeSignature: [4, 4],
    tracks: [
      { id: 1, instrument: "Regência", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-regencia.mp3' },
      { id: 2, instrument: "Vocal", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-vocal.mp3' },
      { id: 3, instrument: "Backing Vocals", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-backing-vocals.mp3' },
      { id: 4, instrument: "Alfaia", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-alfaia.mp3' },
      { id: 5, instrument: "Baixo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-baixo.mp3' },
      { id: 6, instrument: "Berimbau", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-berimbau.mp3' },
      { id: 7, instrument: "Caixa", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-caixa.mp3' },
      { id: 8, instrument: "Conga", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-conga.mp3' },
      { id: 9, instrument: "Cowbell", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-cowbell.mp3' },
      { id: 10, instrument: "Guitarra", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-guitarra.mp3' },
      { id: 11, instrument: "Palmas", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-palmas.mp3' },
      { id: 12, instrument: "Pandeiro", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-pandeiro.mp3' },
      { id: 13, instrument: "Percussões Originais", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-percussoes-originais.mp3' },
      { id: 14, instrument: "Pratos", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-pratos.mp3' },
      { id: 15, instrument: "Triângulo", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-triangulo.mp3' },
      { id: 16, instrument: "Violão", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-violao.mp3' },
      { id: 17, instrument: "Xequerês", path: 'https://media.githubusercontent.com/media/BesouroLAB/albumsankofa/main/ensaio-show/13-pra-cordel-e-nana-poeira/%5B13-pra-cordel-e-nana-poeira%5D-xequeres.mp3' },
    ],
  },
];
